StudentsControl/Models/ViewModels/ImportDataViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentsControl.Models.ViewModels
{
    public class ImportDataViewModel
    {
        public string Nombre { get; set; }
        public List<string> Hojas { get; set; }
    }
}

StudentsControl/Controllers/ImportDataController.cs
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentsControl.Models;
using System.Data.Entity.Core.Objects.DataClasses;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using System.Data;
using StudentsControl.Models.StudentsControlModels;
using EasyXLS;

namespace StudentsControl.Controllers
{
    public class ImportDataController : Controller
    {
        StudentsControlContext db = new StudentsControlContext();
        string directorio = "~/Content/Files/";

        // GET: ImportData
        public ActionResult Index()
        {
            ViewBag.Maestro = "CentrosEducativos";
            return View();
        }

        [HttpPost]
        public ActionResult Upload()
        {
            var myFile = Request.Files["myFile"];
            var targetLocation = Server.MapPath(directorio);

            try
            {
                var path = Path.Combine(targetLocation, Path.GetFileName(myFile.FileName));
                var ExtensionArchivo = Path.GetExtension(myFile.FileName);
                myFile.SaveAs(path);
                TempData["ExtensionArchivo"] = ExtensionArchivo;
            }
            catch
            {
                Response.StatusCode = 400;
            }

            return new EmptyResult();
        }
        public ActionResult ObtenerHojas(string nombreArchivo)
        {
            var targetLocation = Server.MapPath(directorio);
            var path = Path.Combine(targetLocation, Path.GetFileName(nombreArchivo));

            FileStream stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            SpreadsheetDocument spreadSheetDocument = SpreadsheetDocument.Open(path, false);
            TempData["documento"] = spreadSheetDocument;
            TempData["path"] = path;
            WorkbookPart workbookPart = spreadSheetDocument.WorkbookPart;
            IEnumerable<Sheet> sheets = spreadSheetDocument.WorkbookPart.Workbook.GetFirstChild<Sheets>().Elements<Sheet>();

            List<string> listaHojas = new List<string>();
            foreach (Sheet sheet in sheets)
            {
                listaHojas.Add(sheet.Name);
            }

            return Json(listaHojas, JsonRequestBehavior.AllowGet);

        }
        public ActionResult ObtenerRango(string nombreHoja)
        {
            int celdaIni = 0, celdaFin = 0;
            SpreadsheetDocument spreadSheetDocument = (SpreadsheetDocument)TempData["documento"];
            //Obtener Celda Inicio y Fin
            if (nombreHoja != "")
            {
                celdaIni = 1;
                celdaFin = Class_Objetos.GetRowCount(spreadSheetDocument, nombreHoja) - 1;
            }
            var resultJson = new { CeldaIni = celdaIni, CeldaFin = celdaFin };
            return Json(resultJson, JsonRequestBehavior.AllowGet);
        }
        public ActionResult MapeoCampos(string nombreHoja, int filaIni, int filaFin)
        {
            #region Obteniendo Campos de BD
            string instrSQL = "";
            string Tabla = "CentrosEducativos";

            //Ya el Usuario selecciono la tabla, entonces se pueden obtener los Campos en la BD que la conforman
            instrSQL = "SELECT c.COLUMN_NAME AS ColDestino,'' AS ColOrigen,c.DATA_TYPE AS Tipo\n" +
                       $",CASE WHEN k.CONSTRAINT_NAME IS NOT NULL THEN 'PK' END AS PrimaryKey\n" +
                       $"FROM INFORMATION_SCHEMA.COLUMNS c\n" +
                       $"LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k ON c.COLUMN_NAME = k.COLUMN_NAME AND c.TABLE_NAME = k.TABLE_NAME AND c.TABLE_CATALOG = k.TABLE_CATALOG\n" +
                       $"WHERE c.TABLE_NAME = '{Tabla}' \n" +
                       $"AND c.TABLE_CATALOG='{db.Database.Connection.Database}'\n" +
                       $"AND ISNULL(k.CONSTRAINT_NAME,'N') NOT LIKE 'FK%';";
            IEnumerable<MapeoColumnas> data = db.Database.SqlQuery<MapeoColumnas>(instrSQL);
            var properties = data.ToArray();
            
            var ColBDArray = JsonConvert.SerializeObject(properties);
            #endregion
            #region Abriendo Hoja con EasyXLS
            //var stream = (FileStream)TempData["stream"];
            var path = (string)TempData["path"];
            var ExtensionArchivo = (string)TempData["ExtensionArchivo"];

            DataSet result = new DataSet();
            DataTable DTHoja = new DataTable();
            ExcelDocument workbook = new ExcelDocument();
            try
            {
                if (ExtensionArchivo == ".xls")
                    result = workbook.easy_ReadXLSSheet_AsDataSet(path, nombreHoja);
                if (ExtensionArchivo == ".xlsx")
                    result = workbook.easy_ReadXLSXSheet_AsDataSet(path, nombreHoja);
            }
            catch (Exception exs)
            {
                string error = workbook.easy_getError();
            }

            DTHoja = result.Tables[0];
            for (int c = 0; c < DTHoja.Columns.Count; c++)
            {
                string NombreCol = DTHoja.Rows[0][c].ToString();
                try
                {
                    DTHoja.Columns[c].ColumnName = NombreCol;
                }
                catch (Exception exs)
                { break; }
            }
            DTHoja.Rows.RemoveAt(0);
            #endregion

            string str = "";
            if (filaIni != 1) filaIni = filaIni - 2;
            if (filaIni < 0) filaIni = 0;
            List<NombresColumnas> ArrayColumnas = new List<NombresColumnas>();
            NombresColumnas nc = new NombresColumnas();
            nc.NombreColumna = "";
            nc.NombreExcel = "";
            ArrayColumnas.Add(nc);
            for (int c = 0; c < DTHoja.Columns.Count; c++)
            {
                if (filaIni == 1)
                {
                    if (DTHoja.Columns[c] != null)
                        str = DTHoja.Columns[c].ColumnName;
                }
                else
                {
                    if (DTHoja.Rows[filaIni][c] != null)
                        str = DTHoja.Rows[filaIni][c].ToString();
                }
                if (str != "" && str != null)
                {
                    str = str.Trim();
                    str = str.Replace("\"", "");
                    str = str.Replace("'", "");

                    nc = new NombresColumnas();
                    nc.NombreColumna = DTHoja.Columns[c].ColumnName;
                    nc.NombreExcel = str;
                    ArrayColumnas.Add(nc);
                }
            }//Fin Ciclo columnas en Rango Excel

            //var array = DT_cmb.AsEnumerable().ToArray();
            var lookUpjsonArray = JsonConvert.SerializeObject(ArrayColumnas);

            var resultJson = new { dgDataSource = ColBDArray, dgLookUp = lookUpjsonArray };
            return Json(resultJson, JsonRequestBehavior.AllowGet);

        }
    }
}

StudentsControl/Views/ImportData/Index.cshtml
@{
    ViewBag.Title = "Importador Excel";
}

<h2>Importador Excel</h2>
<h3 class="hidden">@ViewBag.Maestro</h3>
<div class="row">
    <div class="col-md-6">
        <div id="Paso1" class="row">
            <h4>Paso 1. Subir Archivo</h4>
            <div id="fileuploader">
                <div id="file-uploader"></div>
                @(Html.DevExtreme().FileUploader()
        .ID("file-uploader")
        .Name("myFile")
        .Multiple(false)
        .Accept("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel")
        .UploadMode(FileUploadMode.Instantly)
        .UploadUrl(Url.Action("Upload", "ImportData"))
        .LabelText("o Arrastre el archivo aqui")
        .SelectButtonText("Seleccione el Archivo")
        .UploadedMessage("Carga Exitosa")
        .UploadFailedMessage("Error en la Carga")
        .OnUploaded("fileUploader_onUploaded")
                )
            </div>
        </div>
        <div id="Paso2" class="row">
            <h4>Paso 2. Seleccionar Hoja</h4>
            <div id="cmbHojas" class="dx-selectbox"></div>
            @(Html.DevExtreme().SelectBox()
                .ID("cmbHojas")
                .Name("cmbHojas")
                .OnValueChanged("cmbHojas_onValueChanged"))
        </div>
        <div id="Paso3" class="row">
            <h4>Paso 3. Definir Rango de Datos</h4>
            <div class="col-md-3">
                Fila Inicial
                @(Html.DevExtreme().TextBox().ID("txtFilaInicial").Name("txtFilaInicial").Value("1"))
            </div>
            <div class="col-md-3">
                Fila Final
                @(Html.DevExtreme().TextBox().ID("txtFilaFinal").Name("txtFilaFinal").Value("1000"))
            </div>
            <div class="col-md-6">
                <br />
                @(Html.DevExtreme().Button().ID("btnActualizar").Text("Actualizar").Type(ButtonType.Default).OnClick("btnActualizar_onClick"))
            </div>
        </div>
        <div id="Paso4" class="row">
            <h4>Paso 4. Mapear Campos y Columnas</h4>
            <div id="dgColumnas" class="dx-datagrid"></div>
            @*@(Html.DevExtreme().DataGrid()
            .ID("dgColumnas")
            .Columns(c=> {
                c.Add().DataField("ColDestino");
                c.Add().DataField("ColOrigen");
                c.Add().DataField("PrimaryKey").Visible(false);
                c.Add().DataField("Tipo").Visible(false);
            }))*@
            <hr />
        </div>
    </div> <!--Fin Mitad Columnas-->
    <div class="col-md-6">
        <div id="Paso5" class="row">
            @(Html.DevExtreme().Button().ID("btnImportar").Text("Importar").Type(ButtonType.Success))
        </div>
    </div>
</div> <!--Fin Fila Principal-->
@section Scripts{
<script>
    // Shorthand for $( document ).ready()
     $(function () {
                $("#Paso2").hide();
                $("#Paso3").hide();
                $("#Paso4").hide();
                $("#Paso5").hide();
            });

    //fileUploader_onUploaded
    function fileUploader_onUploaded(e) {
        var nombreArchivo = e.file.name;
        $.ajax({
            type: "GET",
            url: '@Url.Action("ObtenerHojas", "ImportData")',
            data: { nombreArchivo: nombreArchivo },
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: successUpload,
            error: errorUpload
        });

        function successUpload(data, status) {
            $("#Paso2").show();
            $("#cmbHojas").dxSelectBox("instance").option('items', data);
        }
        function errorUpload() {
            alert('error');
        }
    }

    //cmbHojas_onValueChanged
    function cmbHojas_onValueChanged(e) {
                var nombreHoja = e.value;
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("ObtenerRango", "ImportData")',
                    data: { nombreHoja: nombreHoja },
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: successFunc,
                    error: errorFunc
                });

                function successFunc(data, status) {
                    $("#txtFilaInicial").dxTextBox('instance').option('value', data.CeldaIni);
                    $("#txtFilaFinal").dxTextBox('instance').option('value', data.CeldaFin);

                    $("#Paso3").show();
                }

                function errorFunc() {
                    alert('error');
                }
            }

    //btnActualizar_onClick
    function btnActualizar_onClick(e) {
        var filaIni = $("#txtFilaInicial").dxTextBox("instance").option("value");
        var filaFin = $("#txtFilaFinal").dxTextBox("instance").option("value");
        var nombreHoja = $("#cmbHojas").dxSelectBox("instance").option("value");
       

        $.ajax({
            type: "GET",
            url: '@Url.Action("MapeoCampos", "ImportData")',
            data: { nombreHoja: nombreHoja, filaIni: filaIni, filaFin: filaFin },
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: successFunc,
            error: errorFunc
        });

        function successFunc(data, status) {  
            //Scripts Grids
            var dgDataSource = $.parseJSON(data.dgDataSource);
            var dgLookUp = $.parseJSON(data.dgLookUp);

            $("#dgColumnas").dxDataGrid({
                dataSource: dgDataSource,
                columns: [
                    { dataField: 'ColDestino' },
                    { dataField: 'PrimaryKey', visible: false },
                    { dataField: 'Tipo', visible: false },
                    {
                        dataField: 'ColOrigen'
                        , lookup: { dataSource: dgLookUp, valueExpr: 'NombreExcel', displayExpr: 'NombreColumna' }
                        , allowEditing: true
                    }
                ],
                editing: {
                    allowUpdating: true, // Enables editing
                    mode: "cell"
                }
            });
            $("#Paso4").show();
        }

        function errorFunc() {
            alert('error');
        }
    }
</script>
}